// Define the application root directory........................................
global.APP_ROOT = __dirname

// ...Build Sys.................................................................
require('./_tasks')
